# Site settings
title: Coderidea Blog
SEOTitle: Coderidea的博客 | Coderidea Blog
header-img: img/bg-index.jpg
email: 暂无
description: "关于程序与设计、投资理财 | 这里是Coderidea的个人博客 ，欢迎大家访问，一起交流学习"
keyword: "Coderidea的博客 | Coderidea Blog"
url: "http://tianyaxiang.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/tianyaxiang/tianyaxiang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个程序员的碎碎念~，欢迎扫码关注我的公众号『个人成长之路』，生命不息，学习不止。"
sidebar-avatar: /img/avatar_binggan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     Coderidea
zhihu_username:     meng-chen-58
github_username:    tianyaxiang
#facebook_username:  暂无
#jianshu_username:   暂无
#twitter_username:   tianyaxiang




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


plugins: [jekyll-paginate]
# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
gems: [jekyll-paginate]
paginate: 10




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 6cbaa4389d74519e2e52                            #生成的clientID
  clientSecret: 9ad60699b9b111d887b1510d34418901ca1a0db2    #生成的clientSecret
  repo: tianyaxiang.github.io    #仓库名称
  owner: tianyaxiang    #github用户名
  admin: tianyaxiang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0             # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "博客园",
        href: "https://www.cnblogs.com/xiaoyao2011/"
    },
  {
    title: "CSDN",
    href: "https://blog.csdn.net/tianyaxiang"
  }
]
